### ISSUE TITLE
Enable upsert with multiple key colum

### ISSUE THREAD

**Issue by vigneshtvp** [confluentinc/kafka-connect-bigquery#109]
Hi @C0urante, 

Is upsert logic support for multiple key column.
I am getting error message, when i try to give multiple column on kafkaKeyFieldName.

Sample Kafka message:

{"po_nbr":"3772504775","load_id":87226103,"charge_type_code":1,"batch_nbr":16748,"acctg_type_code":5}{"business_type_code":"PPU  ","trans_mode_code":3,"db_acctg_map_id":12,"cr_acctg_map_id":27,"db_acctg_bu_id":8,"cr_acctg_bu_id":31,"estimated_cost_amt":"0®","rate_factor_percent":"\u0000","last_change_ts":1620093248000,"ship_service_code":null,"receiver_id":{"int":504775},"received_ts":{"long":1619913600000},"pnl_vendor_nbr":{"int":476312956},"pnl_vendor_name":{"string":"REFRESCO BEVERAGES US INC     "},"last_change_userid":"trsys     ","journal_ind":"Y","invc_ex_rsn_code":{"int":121},"fleet_ind":"Y","create_userid":"trsys   ","create_ts":1620093248000}

Sample Configuration properties :

connector.class=com.wepay.kafka.connect.bigquery.BigQuerySinkConnector
autoUpdateSchemas=true
sanitizeTopics=true
autoCreateTables=true
tasks.max=1
topics=acctg_load_po
allowSchemaUnionization=true
upsertEnabled=true
project=***
maxWriteSize=10000
defaultDataset=***
value.converter.schema.registry.url=****
schema.registry.url=****
kafkaKeyFieldName=po_nbr,load_id,charge_type_code,batch_nbr,acctg_type_code
allowNewBigQueryFields=true
keyfile=****
schemaRetriever=com.wepay.kafka.connect.bigquery.retrieve.IdentitySchemaRetriever
value.converter=io.confluent.connect.avro.AvroConverter
key.converter=io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url=***
tableWriteWait=500
intermediateTableSuffix=_tmp
bufferSize=100000

Error message:

Caused by: Invalid field name "po_nbr,load_id,charge_type_code,batch_nbr,acctg_type_code". Fields must contain only letters, numbers, and underscores, start with a letter or underscore, and be at most 300 characters long.
	at com.wepay.kafka.connect.bigquery.write.row.UpsertDeleteBigQueryWriter.attemptTableCreate(UpsertDeleteBigQueryWriter.java:89)
	at com.wepay.kafka.connect.bigquery.write.row.AdaptiveBigQueryWriter.performWriteRequest(AdaptiveBigQueryWriter.java:115)
	at com.wepay.kafka.connect.bigquery.write.row.BigQueryWriter.writeRows(BigQueryWriter.java:118)
	at com.wepay.kafka.connect.bigquery.write.batch.TableWriter.run(TableWriter.java:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Please do let me know whether upsert logic support for multiple key column.

Schema for kafka-key :

{
    "id": 5886,
    "subject": "acctg_load_po-key",
    "version": 1,
    "schema": "{\"type\":\"record\",\"name\":\"ConnectDefault\",\"namespace\":\"io.confluent.connect.avro\",\"fields\":[{\"name\":\"po_nbr\",\"type\":\"string\"},{\"name\":\"load_id\",\"type\":\"int\"},{\"name\":\"charge_type_code\",\"type\":{\"type\":\"int\",\"connect.type\":\"int16\"}},{\"name\":\"batch_nbr\",\"type\":\"int\"},{\"name\":\"acctg_type_code\",\"type\":{\"type\":\"int\",\"connect.type\":\"int16\"}}]}",
    "compatibilityLevel": null
}

**Comment by C0urante** [comment]
As I mentioned on #110, the connector takes the entire key--which must be a struct or map--and stores it under a single nested column with the name specified in the `kafkaKeyFieldName` property. All fields in that struct or map are used as sub-fields of that column.

The connector will automatically use every field in the record's key; the purpose of the `kafkaKeyFieldName` isn't to select a subset of fields from Kafka record keys, but to identify the name of the column in BigQuery that should contain all fields of the record key.

**Comment by vigneshtvp** [comment]
got it @C0urante Thanks for clarifying this question.
