### ISSUE TITLE
enabling upsert logic creating column name as struct type.

### ISSUE THREAD

**Issue by vigneshtvp** [confluentinc/kafka-connect-bigquery#110]
Hi @C0urante,

I have successfully tested  upsert logic on Bigquery sink connector. But Bigquery table created by bigquery sink connector, creating column name which mentioned in  kafkaKeyFieldName  as columnname.columname.

Example :
kafkaKeyFieldName = log_id

Column name in table look like - log_id.log_id integer.

Is there any way i can get only column name. as (log_id) instead of (log_id.log_id )

**Comment by C0urante** [comment]
There's no way to do this at the moment. The connector takes the entire key--which must be a struct or map--and stores it under a single nested column with the name specified in the `kafkaKeyFieldName` property. All fields in that struct or map are used as sub-fields of that column.

It might be useful to expand the connector's key support to accept primitive keys and/or pull out the fields of structured keys directly into the record without putting them all into a single top-level column. I don't have time to commit to implementing this any time soon but could review a PR if someone else wanted to.
