### ISSUE TITLE
Will upsert work on changing kafka topic property

### ISSUE THREAD

**Issue by vigneshtvp** [confluentinc/kafka-connect-bigquery#111]
Please do let  me know, upsert logic on bigquery table will work on changing Kafka topic property?

properties:

topics=transportation.acctg_load_po

on changing above topic using SMT REGEX from transportation.acctg_load_po to acctg_load_po, offset is not committing to consumer group_id.

**Comment by C0urante** [comment]
Unfortunately, upsert/delete mode does not yet work with SMTs that change the name of topics, and a KIP will likely have to be implemented first since this is due to a limitation of the Kafka Connect framework.
