### ISSUE TITLE
Add support for topics with multiple schemas 

### ISSUE THREAD

**Issue by art-i-svsg** [confluentinc/kafka-connect-bigquery#114]
This functionality has been developed in https://github.com/wepay/kafka-connect-bigquery/pull/238, but looks like its abandoned since then. 

Is it possible to integrate this solution into connector?

**Comment by C0urante** [comment]
The connector doesn't support this natively, but it's possible to implement by the use of SMTs that redirect records to topics based on their schemas (or on some other predicate that has a directly correlation with their schema).

Just note that the use of SMTs that change the topic/partition/offset information of a record cannot be used in combination with the `upsert.enabled` and/or `delete.enabled` properties.

**Comment by OuesFa** [comment]
Hi @C0urante 👋 
Can you please share an example of similar use of the SMTs?

**Comment by C0urante** [comment]
Sure, there's one in the quickstart config: https://github.com/confluentinc/kafka-connect-bigquery/blob/ebcf91946944380860a70a60b9b7f12d31e65939/kcbq-connector/quickstart/properties/connector.properties#L31-L38

**Comment by OuesFa** [comment]
Thanks @C0urante, I'm already using this conf in order to route data to the table with the name I want but I can't see how I could use these confs in order to redirect a records from one topic to multiple BQ tables depending on their schema.

**Comment by OuesFa** [comment]
I'm providing a little more context on my usecase, basically I'm using `io.confluent.kafka.serializers.subject.RecordNameStrategy` to write data within my Kafka topics, so I'm wondering if there is a way to specify it to the connector in order to create a separate BQ table for each schema.
I can see [in this comment ](https://github.com/wepay/kafka-connect-bigquery/issues/245#issuecomment-649274542) that you were suggesting to provide a way for users to specify that via a configuration somewhere but I don't know if it's possible or way or another. 
I've to admit that the SMT approach is not clear to me for now.

**Comment by OuesFa** [comment]
Schemas are stored into the Confluent Schema Registry

**Comment by C0urante** [comment]
Ah sorry, I thought you wanted a general demonstration of how to configure an SMT.

For your specific use case I don't know if there is an already-implemented SMT available, but it shouldn't be too hard to implement one that redirects records to different topics based on, e.g., the [name](https://kafka.apache.org/30/javadoc/org/apache/kafka/connect/data/Schema.html#name()) of the record's schema. You can see some examples of how to implement an SMT in the Kafka Connect codebase [here](https://github.com/apache/kafka/tree/trunk/connect/transforms/src/main/java/org/apache/kafka/connect/transforms), including the [RegexRouter](https://github.com/apache/kafka/blob/06dfa54be758e8589e9ce9b2ee67c9721b5b0546/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/RegexRouter.java) and [ExtractField](https://github.com/apache/kafka/blob/06dfa54be758e8589e9ce9b2ee67c9721b5b0546/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/ExtractField.java) SMTs.

**Comment by OuesFa** [comment]
Thanks for the lead. 
Seems that there is no way to have the schema name queried from the schema registry using SMTs 🤔
At least I can't find any SMT using that information and no lead on that part anywhere.

**Comment by OuesFa** [comment]
I just found [this one](https://jcustenborder.github.io/kafka-connect-documentation/projects/kafka-connect-transform-common/transformations/examples/SchemaNameToTopic.example.html) that is promising. 
But I can see in the connector [limitations doc](https://docs.confluent.io/kafka-connect-bigquery/current/overview.html#limitations) that it  

> does not currently support any Single Message Transformations (SMTs) that modify the topic name

Also I can't find the SMT mentioned above within the list of supported SMTs https://docs.confluent.io/cloud/current/connectors/single-message-transforms.html#list-of-available-smts

**Comment by C0urante** [comment]
> Seems that there is no way to have the schema name queried from the schema registry using SMTs 🤔

Doesn't the Confluent Avro converter automatically populate the schema name based on the name of the Avro record it was derived from?

> But I can see in the connector limitations doc that it
> > does not currently support any Single Message Transformations (SMTs) that modify the topic name

I'm sorry, those docs are incorrect and I've reached out to the team that owns them to see about publishing a correction. The connector works fine with SMTs that modify topic/partition/offset, _unless_ you are running with upsert/delete enabled (i.e., `upsertEnabled` and/or `deleteEnabled` are `true` in the connector config).

**Comment by OuesFa** [comment]
Thanks for your answer ! 
Indeed it works well using that SMT
It was not easy to figure out the exact configs to use but here it is, simply: 
```
          transforms: "SchemaNameToTopic"
          transforms.SchemaNameToTopic.type: "com.github.jcustenborder.kafka.connect.transform.common.SchemaNameToTopic$Value"
```
> and RegexRouter can be used as an optional follow-up in case you want to route to a table whose name doesn't exactly match the name of the record's schema.

Good idea I didn't think about that, thanks!
