### ISSUE TITLE
Connector fails when using decorator syntax against non-DAILY partitioned tables

### ISSUE THREAD

**Issue by C0urante** [confluentinc/kafka-connect-bigquery#138]
Based on https://cloud.google.com/bigquery/streaming-data-into-bigquery#ingestion-time_partitioning, it turns out that BigQuery doesn't allow streaming inserts to target specific partitions of ingestion time-partitioned tables using decorator syntax unless the table is partitioned on day. So, the new changes to support the HOUR, MONTH, and YEAR partitioning types in https://github.com/confluentinc/kafka-connect-bigquery/pull/61 are mostly unnecessary and, at worst, can actually mislead users.

To address this we should:
1. Revert the functional changes in that PR that attempt to add support for decorator syntax when writing to non-daily-partitioned tables
2. Add integration tests to the connector that verify its ability to write to tables with various styles of time partitioning with the cases that we believe we do support

**Comment by C0urante** [comment]
There may be an alternative here that can actually maintain support for message time partitioning with non-`DAY`-partitioned tables. We may be able to overwrite the `_PARTITIONTIME` pseudocolumn on writes to BigQuery instead of using decorator syntax. I haven't tested this at all yet but will try to do so as part of this issue since that should be easier to do once integration tests for time partitioning support are added.

**Comment by C0urante** [comment]
Unfortunately, it looks like overwriting the `_PARTITIONTIME` pseudocolumn is not supported for streaming inserts. We'll have to disable decorator syntax for any tables that aren't partitioned by day, and throw an error on startup if the configured time partitioning type is anything except `DAY`.

**Comment by ideasculptor** [comment]
So this means it is entirely not possible to partition on anything other than `DAY` or just that someone wanting to partition by a different granularity has to configure it in some other way? It's not clear from the commentary here.

**Comment by C0urante** [comment]
It's still possible to use the connector to write to ingestion-time partitioned tables with any granularity (hour, day, month, etc.), but unless the table is partitioned by day, it cannot be configured with `bigQueryPartitionDecorator` set to `true`. The only practical implication of this as far as I know is that it means the connector cannot be used to explicitly write to partitions corresponding to the record timestamp (accomplished by enabling the decorator config property described earlier and setting `bigQueryMessageTimePartitioning` to `true`).

**Comment by C0urante** [comment]
Addressed by https://github.com/confluentinc/kafka-connect-bigquery/pull/141
