### ISSUE TITLE
Confusion in documentation regarding to the use of RegexRouter for topic to table mapping

### ISSUE THREAD

**Issue by albantsui** [confluentinc/kafka-connect-bigquery#167]
Regarding to documentation, in the section about 2.0.0 upgrade that now you have to use `RegexRouter` to map the topic name to “table name" 

https://docs.confluent.io/kafka-connect-bigquery/current/overview.html#upgrading-to-2-0-0

but at the top of the same page, the limitation https://docs.confluent.io/kafka-connect-bigquery/current/overview.html#limitations, says that `org.apache.kafka.connect.transforms.RegexRouter` is not an allowed transformation!

Please clarify.

**Comment by C0urante** [comment]
This was raised yesterday in https://github.com/confluentinc/kafka-connect-bigquery/issues/114#issuecomment-972682941. If you check now, those docs should have been updated to now state that those restrictions only apply with upsert/delete enabled, which was introduced in 2.0.0 (after the topics-to-tables routing feature was removed).
