### ISSUE TITLE
Support for BQ Storage Streaming Write API

### ISSUE THREAD

**Issue by nmatare** [confluentinc/kafka-connect-bigquery#169]
Google is deprecating the legacy InsertAll method in favor of the newer BigQuery Storage Streaming Write API (v1 or v2)

It would be wonderful if Confluent would support this newer upload method...

ref:  https://cloud.google.com/bigquery/docs/write-api

**Comment by C0urante** [comment]
Duplicate of https://github.com/confluentinc/kafka-connect-bigquery/issues/100.

But noted :)
