### ISSUE TITLE
Column names matching bigquery reserved keywords cause failure

### ISSUE THREAD

**Issue by ander7en** [confluentinc/kafka-connect-bigquery#175]
Hi. So I have a setup where data is pulled from postgresql using debezium and sinked into BigQuery. One of the tables has a column named `hash` which causes the following error on BigQuery side:
```
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "location" : "q",
    "locationType" : "parameter",
    "message" : "Syntax error: Unexpected keyword HASH at [1:672]",
    "reason" : "invalidQuery"
  } ],
  "message" : "Syntax error: Unexpected keyword HASH at [1:672]",
  "status" : "INVALID_ARGUMENT"
}
```
This is one particular edge case that I have encounter but I assume that other reserved keywords would lead to the same outcome.

Connector version: 2.1.10
Config values:
```
autoCreateTables: true
bigQueryRetry: 10
sanitizeTopics: true
allBQFieldsNullable: true
upsertEnabled: true
deleteEnabled: true
allowNewBigQueryFields: true
allowBigQueryRequiredFieldRelaxation: true
allowSchemaUnionization: true
kafkaKeyFieldName: kafka_key
mergeIntervalMs: 15_000
mergeRecordsThreshold: 1000
queueSize: 40_000
errors.retry.timeout: -1
errors.log.enable: true
errors.log.include.messages: true
```

Is it possible to avoid this issue by having proper escaping around column names?

**Comment by ander7en** [comment]
there seems to be a PR for it as somebody encountered the same issue with different reserved keyword https://github.com/confluentinc/kafka-connect-bigquery/pull/174

**Comment by C0urante** [comment]
Addressed via https://github.com/confluentinc/kafka-connect-bigquery/pull/174
