### ISSUE TITLE
[BUG] batch mode - batchLoadIntervalSec not working

### ISSUE THREAD

**Issue by raphaelauv** [confluentinc/kafka-connect-bigquery#189]
`batchLoadIntervalSec` is not respected by the connector 

```json
{
  "name": "bq-connect1",
  "config": {
    "connector.class": "com.wepay.kafka.connect.bigquery.BigQuerySinkConnector",
    "tasks.max": "1",
    "topics.regex": "dbserver_mysql.inventory.*",
    "keySource": "FILE",
    "keyfile" : "/secrets/gcp/credentials.json",
    "sanitizeTopics": "true",
    "autoCreateTables": "true",
    "autoUpdateSchemas": "true",
    "enableBatchLoad": "true",
    "includeKafkaData" : "true",
    "batchLoadIntervalSec": 1200,
    "allowNewBigQueryFields": "true",
    "allowSchemaUnionization": "false",
    "schemaRetriever": "com.wepay.kafka.connect.bigquery.retrieve.IdentitySchemaRetriever",
    "project": "xxxx",
    "gcsBucketName": "xxxx",
    "defaultDataset": "xxxx"
  }
}
```

when I publish a new event in Kafka , I see the row in Bigquery around a minute after. The connector seam impacted by the worker setting `offset.flush.interval.ms`.

Missing 2 things : 

- The connector should not load gcs files to BQ before the end of the inverval 

- The connector is missing settings to manage the files written to gcs before loading to BQ  :

      - flush.size : Number of records written to store before invoking file commits.
      - gcs.part.size: Size of a part of a final object to write to gcs

**Comment by jeonguihyeong** [comment]
your setting is wrong.  "enableBatchLoad": "true" it is not true or false option. it is topic name that you need to write down

**Comment by raphaelauv** [comment]
Thanks for your answer , that's is a very confusion name :sweat_smile: 

but that setting is not compatible with a regex (and since I use topics.regex) that is not efficient

I will open another issue.

Thanks again for your help
