### ISSUE TITLE
Operation info. 

### ISSUE THREAD

**Issue by Singh-Lovepreet** [confluentinc/kafka-connect-bigquery#44]
Hi, I want to use kcbq but I have doubt that is it just perform insert data operation or also perform update data operation in big query.

for the new record it performs insert operation and for update operation is it perform update or again perform insert only.

**Comment by C0urante** [comment]
@Singh-Lovepreet the current `master` of the connector does support upsert and delete operations but we haven't performed an official release for it yet. You can give these a try by building from the latest `master` or the `2.0.x` branch (they're functionally identical at the moment) and toggling the `upsert.enabled` and `delete.enabled` configuration properties. With this feature enabled, the connector will use the keys of records it reads from Kafka to identify rows in BigQuery that should be updated/deleted.

Note that this feature is implemented by streaming data into intermediate tables before it makes its way into the table that the connector is configured to write to. This has a few implications: the connector will create more tables than it would without upsert/delete being enabled, and there will be increased latency in the time it takes data to appear in BigQuery. As a result, **be careful with this feature**.
