### ISSUE TITLE
Modify and delete columns in source database

### ISSUE THREAD

**Issue by Ace-Bansal** [confluentinc/kafka-connect-bigquery#48]
Is dropping and modifying columns allowed using this sink connector (since BigQuery doesn't allow dropping and modifying columns in an existing table). I've tested the edge case of adding columns in my database and that gets reflected in my BigQuery warehouse, however I'm not able to delete and modify columns since the BigQuery connector is throwing an error which says that the provided schema isn't correct (after I drop/modify the columns).

I'm using Confluent platform 5.5.1 and the [sink connector that is provided by Counfluent Hub](https://docs.confluent.io/current/connect/kafka-connect-bigquery/index.html)

**Comment by C0urante** [comment]
@Ace-Bansal the limitation here is in what BigQuery permits, not in what the connector is capable of. As their [documentation](https://cloud.google.com/bigquery/docs/managing-table-schemas) states:

> BigQuery natively supports the following schema modifications:
    - Adding columns to a schema definition
    - Relaxing a column's mode from `REQUIRED` to `NULLABLE`
All other schema modifications are unsupported and require manual workarounds

If you have to perform other schema modifications like dropping a column or modifying its type, I'd suggest you do so manually (likely by following the [steps suggested by Google](https://cloud.google.com/bigquery/docs/manually-changing-schemas)). It wouldn't be impossible to add some logic to do those modifications automatically to the connector, but it would be incredibly complicated and there would likely be edge cases and gaps in functionality where things don't work as expected. As a result, I don't believe such a feature would be a good fit for the connector.
