### ISSUE TITLE
Upgrade bigquery to version 1.119.0

### ISSUE THREAD

**Issue by mubeen** [confluentinc/kafka-connect-bigquery#59]
Hi,

I am currently experiencing an issue whereby version 1.79.0 of the google-cloud-bigquery artefact only supports partitioning against the DAY partitioning type, this has been resolved in version 1.119.0 of the artefact.

Is there a way to upgrading the version to 1.119.0 to get the support all of the partitioning types? Are there concerns that I need to be aware of that has prevented the upgrade to later version of this library?

Thanks in advance.

**Comment by C0urante** [comment]
Did some digging, looks like partitioning by hour was added in https://github.com/googleapis/java-bigquery/pull/336 and first released with version 1.114.0, and partitioning by month and year was added in https://github.com/googleapis/java-bigquery/pull/737 and first released with version 1.119.0.

@mubeen I can't say with certainty that upgrading from 1.79.0 to 1.119.0 wouldn't break anything, but if Google follows semantic versioning with their BigQuery Java SDK, the only risk would be from bugs introduced by new features (as opposed to breaking changes). I wouldn't be opposed to bumping the version the connector uses as long as we can confirm that that's the case, and do some testing of our own against that new version to make sure that no obvious bugs would be introduced with it.

However, I'm not sure that we'd get much from just bumping the version; we'd also have to make changes to the connector itself if we wanted to add the same support for non-day partitioning types that we have at the moment for day-based partitioning. I'd be happy to review a PR to do that (or review a design proposal if one is warranted) if you or anyone else would like to implement those changes.

**Comment by mubeen** [comment]
Hi @C0urante I have created a pull request, could you please review the PR

**Comment by mubeen** [comment]
Hi @C0urante new pull requested created against master as requested.

**Comment by C0urante** [comment]
Addressed via https://github.com/confluentinc/kafka-connect-bigquery/pull/61
