### ISSUE TITLE
[question] batch insert 1000 rows into bigquery

### ISSUE THREAD

**Issue by arickbro** [confluentinc/kafka-connect-bigquery#67]
how to configure kafka-connect-bigquery to batch 1000 rows into bigquery?

**Comment by C0urante** [comment]
I don't think that's possible right now. You can control the maximum number of records that get polled from Kafka at a time with recent versions of the Connect framework via the `consumer.override.max.poll.records` property, but that will only set a fixed bound on the total number of rows written for each read to Kafka (which might span several tables).

**Comment by C0urante** [comment]
Closing as the question has been addressed; feel free to reopen if there's more to discuss.
