### ISSUE TITLE
2.0.0 Release to Confluent Hub

### ISSUE THREAD

**Issue by SajanaW** [confluentinc/kafka-connect-bigquery#71]
We're working on cutting a ``2.0.0`` to Confluent Hub, which includes breaking changes from 1.6. In line with this we're also updating the confluent docs for the connector. I'm just opening this issue in case, folks have things to add, questions to ask and so on. 

**We've documented the following breaking changes:**

1. ``datasets`` has been removed, and ``defaultDataset`` has been introduced. The connector now infers the dataset from the topic name if the topic is in the form ``<dataset>:<tableName>``; if the topic name is in the form ``<tablename>``, it defaults to ``defaultDataset``. 

2.  ``topicsToTables`` has been removed. SMTs should be used route topics to tables.
3.  ``autoUpdateSchemas`` has been replaced by ``allowNewBigQueryFields`` and ``allowBigQueryRequiredFieldRelaxation``.

**And we've documented the following new configuration added:** 

1. ``upsertEnabled`` and ``deleteEnabled``
2. ``intermediateTableSuffix`` 
3. ``mergeIntervalMs`` and ``mergeRecordsThreshold``
3.  ``autoCreateBucket``

**questions**
The confluent documentation states that ``enableBatchLoad`` is a beta feature. Is this still true?

**Comment by C0urante** [comment]
We should also make sure to get a fix in for https://github.com/confluentinc/kafka-connect-bigquery/issues/68 before putting out the release. Working on that right now.

**Comment by SajanaW** [comment]
2.0.0 has been released on Confluent Hub. 

In addition to the changes documented above, we also made `IdentitySchemaRetriever` the default `SchemaRetriever` (#75 )
#68 was also included!
