### ISSUE TITLE
In v2.0.x, what schemaRetriever to use to allow automatic schema updates

### ISSUE THREAD

**Issue by discordiaZA** [confluentinc/kafka-connect-bigquery#75]
In v2.0.x, there doesn't appear to be a built in schemaRetriever to facilitate automatic schema updates. I am assuming the `IdentitySchemaRetriever` won't work (since otherwise I assume it would be the default config option). Could some please confirm if this is correct?

**Comment by C0urante** [comment]
> I am assuming the IdentitySchemaRetriever won't work (since otherwise I assume it would be the default config option).

I guess this didn't come up during the previous rounds of work to change how schemas and datasets are extracted from records, but it sounds reasonable to me.

@criccomini @mtagle @stoynov96 @SajanaW what would you think about making the `IdentitySchemaRetriever` the default schema retriever from 2.0.0 onward?

**Comment by C0urante** [comment]
We've made the `IdentitySchemaRetriever` the default now, so marking this closed.
