### ISSUE TITLE
Support configurable time partitioning types for created tables

### ISSUE THREAD

**Issue by C0urante** [confluentinc/kafka-connect-bigquery#80]
Follow-up to [discussion](https://github.com/confluentinc/kafka-connect-bigquery/pull/61#issuecomment-757980726) on #61.

Since the connector now has support for writing to tables with the `HOUR`, `MONTH`, and `YEAR` time partitioning types (in addition to the `DAY` type, which it has supported for a few years now), users should be able to control the time partitioning type it uses for tables it creates. This will likely involve a new configuration property such as `timePartitioningType` with permitted case-insensitive values `HOUR`, `DAY` (default to preserve backwards compatibility), `MONTH`, and `YEAR.

**Comment by mubeen** [comment]
@C0urante 

I will start looking at this in the coming week.

**Comment by C0urante** [comment]
@mubeen thanks, but I'd like to take this one on myself as we'd like to put out a 2.1.0 release by the end of next week.

**Comment by mubeen** [comment]
@C0urante understood, if I can assist in anyway please let me know :)

**Comment by C0urante** [comment]
Addressed via https://github.com/confluentinc/kafka-connect-bigquery/pull/84
