### ISSUE TITLE
Table name and topic name high coupling ?

### ISSUE THREAD

**Issue by jtriq** [confluentinc/kafka-connect-bigquery#95]
Hi guys,

As far as I have seen/understood, the only way to set the bigquery table name is via topic name, am I right ?

I've read the documentation, and  connector pages, and it seems really strange to me that it's not possible to set the table name on the connector configuration. If so (if didn't miss this part), Is there any reason for it ?

Many thanks

**Comment by C0urante** [comment]
Hi @jtriq--the default behavior of the connector is to use the name of the topic as the name of the table it writes to, that's correct. For finer-grained control, we recommend that users configure their connector with an SMT (such as the `RegexRouter`) that changes the names of topics for sink records that are sent to the connector.

We added some detail on this in our 2.0.0 upgrade notes for the connector: https://docs.confluent.io/kafka-connect-bigquery/current/index.html#upgrading-to-2-0-0

**Comment by jtriq** [comment]
Thank you @C0urante i will take a look !
